    mytestkey=This value is from LOCAL properties file

paypal.client.id=${CLIENT_ID}
paypal.client.secret=${CLIENT_SECRET}

paypal.oauth.url=https://api-m.sandbox.paypal.com/v1/oauth2/token

paypal.create.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.capture.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture