mytestkey=This value is from LOCAL properties file

paypal.client.id=AWo5eGT8dJ8z4wv295DWA8WNSidMcTLlPxQDEr1ZusqkdbOIIELPPTcg-hGGWoadE5aljHJCgl5ZB_sN
paypal.client.secret=AWo5eGT8dJ8z4wv295DWA8WNSidMcTLlPxQDEr1ZusqkdbOIIELPPTcg-hGGWoadE5aljHJCgl5ZB_sN

paypal.oauth.url=https://api-m.sandbox.paypal.com/v1/oauth2/token
paypal.create.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders
